### PR TITLE
fix: use imagePullPolicy Always in preview fixes: #17

### PR DESCRIPTION
**Pull request by yelhouti**

### CODE REVIEW

**Comment by rawlingsj** [comment]
By default previews use a PR build number in the image tag that's used in the preview environment, that way each build / image is unique.  Given that I'm not sure if we'd need to `Always` pull images?  Is there more info on why we should default to Always?

**Comment by yelhouti** [comment]
@rawlingsj yes, what happens is that if a build succeeds but the e2e tests for example fails or a typo is fixed afterward or anything, the new image is built but not used by preview ...

**Comment by hervelemeur** [comment]
Also sometime build number is rebooted to a previous number.

**Comment by yelhouti** [comment]
As per discussion in slack, it's better to fix the reset number issue

**Pull request closed without merging**
