### PR TITLE
fix: use toYaml instead of 'range' for environment variables, and ali…

### PR DESCRIPTION
**Pull request by hervelemeur**
…gnment between 'charts' and 'helm' folders  
  
Related:

jenkins-x-buildpacks/jenkins-x-kubernetes#99  
jenkins-x-buildpacks/jenkins-x-kubernetes#101

### CODE REVIEW

**Comment by peter-poki** [comment]
Hi, if you setup env as:
```
 env:
        - name: VERSION
          value: {{ .Chart.Version }}
{{ toYaml .Values.env | indent 10 }}
```

It isn't valid helm chart, helm lint fails on this, just tried it on my cluster. Good approach can be to move this VERSION env variable into `values.yaml` maybe?

**Comment by peter-poki** [comment]
And also ` | indent 8` changes my chart to invalid, I have to have it at 10, to pass `helm lint`

**Comment by hervelemeur** [comment]
@peter-poki I've fixed the indents.

About the VERSION, I didn't have any problem with a deployment as it is, would you mind retest it again?

**Comment by peter-poki** [comment]
Hi @hervelemeur , so problem with linting with VERSION is only when I have in `values.yaml` just `env:` .
If I edit this to (have at least one variable)
```
env:
  - name: "t"
   value: "v"
````
Then it works as expected

**Comment by hervelemeur** [comment]
@peter-poki ah ok, I've tested with a dummy value, will check without any if something can be done

**Comment by hervelemeur** [comment]
@peter-poki I've added a check on `.Values.env` to avoid error if there is no env variables defined in values.yaml

I've also added this check on envFrom for alignment (not mandatory)

**Comment by msvticket** [comment]
This has moved

**Pull request closed without merging**
